CREATE TABLE DOSSIER (
    ID int (11) AUTO_INCREMENT PRIMARY KEY,
    DATE_CREATION DATE
);

CREATE TABLE CLIENT(
    ID int (11) AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    ADRESSE VARCHAR(50),
    TEL VARCHAR(50),   
    DOSSIER INT(11),
    CONSTRAINT FOREIGN KEY (DOSSIER) REFERENCES DOSSIER(ID) DEFAULT NULL
);

CREATE TABLE AFFAIRE(
    ID int (11) AUTO_INCREMENT PRIMARY KEY,
    MOTIF VARCHAR(50),
    DATE_CREATION DATE,
    HONORAIRES VARCHAR(50),
    REST_PAIEMENT DECIMAL(8.2) DEFAULT 0,
    DOSSIER INT(11),
    CONSTRAINT FOREIGN KEY (DOSSIER) REFERENCES DOSSIER(ID) DEFAULT NULL
);

CREATE TABLE AUDIENCE(
    ID int (11) AUTO_INCREMENT PRIMARY KEY,
    DATE_AUDIENCE DATE,
    VERDICT VARCHAR(50) DEFAULT NULL,
    VILLE VARCHAR(50),
    INSTANCE VARCHAR(50),
    AFFAIRE INT(11),
    CONSTRAINT FOREIGN KEY (AFFAIRE) REFERENCES AFFAIRE(ID) DEFAULT NULL
);

CREATE TABLE PIECE(
    ID int (11) AUTO_INCREMENT PRIMARY KEY,
    CHEMIN_IMG VARCHAR(50),
    AFFAIRE INT(11),
    CONSTRAINT FOREIGN KEY (AFFAIRE) REFERENCES AFFAIRE(ID) DEFAULT NULL

);